# Generated by Django 4.0.5 on 2022-07-06 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formsandblog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact_us',
            name='flag',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
