# Generated by Django 4.0.5 on 2022-07-11 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formsandblog', '0003_author_category_alter_contact_us_flag_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='date_update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
