# Generated by Django 4.0.5 on 2022-07-11 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formsandblog', '0004_blog_date_update'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='date_update',
            new_name='date_updated',
        ),
    ]
